SELECT * FROM TEMPORARY;
SELECT * FROM TEMPORARYLOG;
DELETE FROM TEMPORARYLOG;
DESC TEMPORARY;

UPDATE TEMPORARY SET CONTACTPAIRID = 90, DATEIN = (TO_DATE('2020/11/10 08:03:24','YYYY/MM/DD HH24:MI:SS')), ISREACHABLE = 1, LOCATIONID = 140;

SELECT * FROM TEMPORARY WHERE DATEIN =TO_DATE('2020/11/09 08:41:05','YYYY/MM/DD hh24:mi:ss');

CREATE OR REPLACE TRIGGER contact_tracing_aduit_trg 
AFTER UPDATE ON TEMPORARY
FOR EACH ROW
DECLARE 
	
   PRAGMA AUTONOMOUS_TRANSACTION;
    V_CONTACTPAIRID TEMPORARY.CONTACTPAIRID%TYPE;
	V_DATEIN	TEMPORARY.DATEIN%TYPE;
	V_LOCATIONID  TEMPORARY.LOCATIONID%TYPE;
	V_ISREACHABLE TEMPORARY.ISREACHABLE%TYPE;
	EX_TEM_INVAILD EXCEPTION; /*RAISE EXCEPTION WHEN TEMPORARY.ISREACHABLE IS NOT 1 AND 0*/
      

	CURSOR C_TEMPORARY IS
		SELECT CONTACTPAIRID, DATEIN, LOCATIONID, ISREACHABLE FROM TEMPORARY WHERE ISREACHABLE = V_ISREACHABLE;

	
BEGIN   
  OPEN C_TEMPORARY;
  LOOP
    FETCH C_TEMPORARY INTO V_CONTACTPAIRID, V_DATEIN, V_LOCATIONID, V_ISREACHABLE;
   
    IF C_TEMPORARY%FOUND THEN 
      DBMS_OUTPUT.PUT_LINE('Fetchd row: ContactID:'|| V_CONTACTPAIRID || ', Date:' || V_DATEIN || 'Location:' || V_LOCATIONID);
    
      /**if ISREACHABLE equal to 1, then do store the all attributes 		TEMPORARY have into TEMPORARYLOG  **/
        IF V_ISREACHABLE = 1
        THEN
        DBMS_OUTPUT.PUT_LINE('ISREACHABLE MUST BE 0 OR 1!');     

          /**if ISREACHABLE equal to 0, then store the attributes to 		CONTACTLIST that TEMPORARY matched, and store the all 				attributes temporary have into TEMPORARYLOG **/
        ELSIF V_ISREACHABLE = 0 
        THEN    
          INSERT INTO CONTACTLIST(DATEIN, LOCATIONID)
            SELECT DATEIN, LOCATIONID
            FROM TEMPORARY;

            INSERT INTO TEMPORARYLOG(CONTACTPAIRID, DATEIN, ISREACHABLE, LOCATIONID)
            SELECT CONTACTPAIRID, DATEIN, ISREACHABLE, LOCATIONID
            FROM TEMPORARY;
            DELETE FROM TEMPORARY WHERE ISREACHABLE = 0;

       		/**if ISREACHABLE NOT equal to 1 and 0, then raise the 			user-defined exception **/   
        ELSIF V_ISREACHABLE != 1 AND V_ISREACHABLE != 0 THEN
          RAISE EX_TEM_INVAILD;

           END IF;
		ELSE
          EXIT;
        END IF;
       END LOOP;
       CLOSE C_TEMPORARY;
          
EXCEPTION
      WHEN EX_TEM_INVAILD THEN
        DBMS_OUTPUT.PUT_LINE('ISREACHABLE MUST BE 0 OR 1!');
        COMMIT;
    END;
      /